### ISSUE TITLE
Plugin icon oversized

### ISSUE THREAD

**Issue by yoyurec** [c6p/logseq-habit-tracker#18]
Toolbar icon too big )
![image](https://user-images.githubusercontent.com/137919/184433231-ad21e3fe-4589-4c6c-a55c-e9ce90852de0.png)

Make it smaller:
```css
#logseq-habit-tracker--show-habits .button {
    font-size: 20px;
}
```
